site_name: EMS-ESP
site_description: Documentation (Wiki) for EMS-ESP
site_url: https://docs.emsesp.org/
repo_name: 'emsesp/EMS-ESP32'
repo_url: 'https://github.com/emsesp/EMS-ESP32'
edit_uri: 'https://github.com/emsesp/docs/blob/master/docs/'
docs_dir: docs
copyright: 'Copyright &copy; 2025 emsesp.org'

# Enable strict mode for better error detection
# strict: true

plugins:
  - search
  - alternate-link
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - redirects:
      redirect_maps:
        # Add your redirect mappings here
  - table-reader
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  # - git-committers:
  #     repository: emsesp/docs
  #     branch: main

theme:
  name: material
  language: 'en'
  # custom_dir: 'overrides'
  logo: '_media/logo/boiler.svg'
  favicon: _media/favicon.ico

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

  font:
    text: Barlow
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/3J3GgnzpyT'
      name: Discord
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/emsesp/EMS-ESP32'
      name: GitHub

  analytics:
    provider: google
    property: G-SVDSJ3QTVC

  # version:
  #   provider: mike

  generator: false

  # Additional Material theme options
  tags:
    - name: installation
      description: Installation guides and setup instructions
    - name: configuration
      description: Configuration and setup guides
    - name: devices
      description: Supported devices and hardware
    - name: integrations
      description: Third-party integrations and APIs
    - name: troubleshooting
      description: Troubleshooting guides and solutions

markdown_extensions:
  # Core extensions
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Navigation and structure
  - toc:
      permalink: '~'
      permalink_title: 'Link to this section'
      toc_depth: 3
      title: 'On this page'

  # Text formatting
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - def_list
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists

  # Metadata
  - meta

extra_css:
  - 'assets/css/anchor-fix.css'
  - 'assets/css/github.css'
  - 'assets/css/emsesp.css'

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - extra_javascript/tablesort.js
  - extra_javascript/github.js

nav:
  - Home:
      - News: index.md
      - About: About.md
      - Installing: Installing.md
      - Configuring: Configuring.md
      - WebUI: WebUI.md
      - MQTT: MQTT.md
      - Commands: Commands.md
      - Console: Console.md
      - Special Functions: Special-Functions.md
      - Supported EMS Devices: All-Devices.md
      - EMS Devices and Entities: All-Entities.md
      - EMS Telegrams: EMS-Telegrams.md
      - Integrations: Integrations.md
      - Help and Support: Support.md
      - Tips & Tricks: tips-and-tricks.md
      - For Developers: Building.md

  - Devices:
      - Introduction: All-Devices.md
      - Boilers: Boilers.md
      - Thermostats: Thermostats.md
      - Controllers Modules: Controllers.md
      - Heat Pumps: Heat-Pumps.md
      - Alert Modules: Alert.md
      - Connect Modules: Connect.md
      - Extension Modules: Extension.md
      - Gateway Modules: Gateways.md
      - Mixer Modules: Mixer-Modules.md
      - Solar Modules: Solar-Modules.md
      - Switch Modules: Switches.md

  - Integrations:
      - 3rd party integrations: Integrations.md
      - Home Assistant: Home-Assistant.md
      - IOBroker: IOBroker.md
      - Domoticz: Domoticz.md
      - openHAB: openHAB.md
      - Loxone: Loxone.md
      - Grafana: Grafana.md
      - Modbus: Modbus.md

  - Modbus:
      - Introduction: Modbus.md
      - Settings: Modbus-Settings.md
      - Entity Registers: Modbus-Entity-Registers.md
      - Register Blocks: Modbus-Register-Blocks.md
      - Server IDs: Modbus-Server-IDs.md
      - System Server: Modbus-System-Server.md

  - Help:
      - Support: Support.md
      - Troubleshooting: Troubleshooting.md
      - FAQ: FAQ.md

  - Developers:
      - Building & Testing the Firmware: Building.md
      - Adding Languages: Adding-Languages.md
      - Contributing: Contributing.md
      - The EMS protocol: EMS-bus.md
      - EMS Library: ems-library.md
      - Building an EMS circuit: EMS-Circuit.md
      - Version Release History: Version-Release-History.md

# Additional configuration for better compatibility
use_directory_urls: true
dev_addr: '127.0.0.1:8001'
